# SPDX-License-Identifier: MIT
# mypy for the development-only Python tooling. Strict, with no per-module relaxations;
# tools/check_gates.py rejects ignore_errors, disabled error codes and module overrides.
[mypy]
python_version = 3.12
files = tools, tests
mypy_path = tools
strict = True
warn_unreachable = True
enable_error_code = ignore-without-code, redundant-expr, truthy-bool, possibly-undefined, redundant-self, unused-awaitable, explicit-override
extra_checks = True
