// SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
// SPDX-License-Identifier: MIT
// Generated by tools/generate_spec.py. Edit spec/cli-contract.json instead.
#pragma once
#include "docenhance/contract/command.hpp"

#include <algorithm>
#include <array>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>
#include <variant>
namespace docenhance::contract {
inline constexpr unsigned response_schema_version = 3U;
inline constexpr auto input_support = std::to_array<InputSupport>({
    {.format = "png", .binary = true},
    {.format = "jpeg", .binary = false},
});
// The usage line of every command, as the reviewed contract states it.
[[nodiscard]] constexpr std::string_view command_usage(Command command) noexcept {
    switch (command) {
    case Command::root:
        return "docenhance COMMAND [OPTIONS]";
    case Command::process:
        return "docenhance process INPUT --out-dir DIRECTORY [--output-mode "
               "preserve|gray|bw] [OPTIONS]";
    case Command::verify:
        return "docenhance verify DIRECTORY [--json]";
    case Command::methods:
        return "docenhance methods [ID] [--json]";
    case Command::version:
        return "docenhance version [--json]";
    }
    return {};
}
using OptionBinding = std::variant<bool Invocation::*, std::string Invocation::*,
                                   std::optional<std::string> Invocation::*>;
struct OptionDescriptor {
    std::string_view name;
    std::string_view metavar;
    CommandSet scope;
    std::string_view group;
    std::string_view domain;
    std::string_view methods;
    std::string_view description;
    OptionBinding binding;
};
// Descriptions are long single-line literals; keep one option per line.
// clang-format off
inline constexpr auto option_catalog = std::to_array<OptionDescriptor>({
    {.name = "--out-dir", .metavar = "DIRECTORY", .scope = CommandSet{Command::process}, .group = "Processing arguments", .domain = "Required; a new result directory", .methods = "", .description = "Paths must be well-formed UTF-8 and are never normalized or repaired. Parent must exist. Publish result.png into a new directory only after complete processing. Existing destinations are never replaced.", .binding = &Invocation::output_directory},
    {.name = "--output-mode", .metavar = "MODE", .scope = CommandSet{Command::process}, .group = "Output arguments", .domain = "preserve; preserve|gray|bw", .methods = "", .description = "Preserve keeps the decoded gray/color category, not source bytes, ICC space, metadata or alpha. Continuous output has no enhancement filter and is verified before publication. Gray converts linear luminance; bw explicitly activates stored-sample binarization. JPEG input supports preserve/gray only; bw requires grayscale PNG.", .binding = &Invocation::output_mode},
    {.name = "--bit-depth", .metavar = "DEPTH", .scope = CommandSet{Command::process}, .group = "Output arguments", .domain = "auto; auto|8|16", .methods = "", .description = "Continuous output only. Auto retains 16-bit source precision, otherwise 8. Explicit 16-to-8 reduction is reported; no precision fallback is used for resource limits.", .binding = &Invocation::bit_depth},
    {.name = "--alpha", .metavar = "MODE", .scope = CommandSet{Command::process}, .group = "Output arguments", .domain = "white; white|black|reject", .methods = "", .description = "Continuous output only. Composite straight PNG alpha over white or black in linear light; reject refuses any non-opaque pixel. Output is opaque.", .binding = &Invocation::alpha},
    {.name = "--profile-policy", .metavar = "POLICY", .scope = CommandSet{Command::process}, .group = "Output arguments", .domain = "embedded; embedded|srgb", .methods = "", .description = "Continuous output only. Interpret supported cICP, compatible ICC, sRGB or gAMA/cHRM; otherwise report an sRGB assumption. srgb explicitly overrides color declarations, not integrity or orientation checks. Unsupported HDR/cICP is rejected by embedded policy.", .binding = &Invocation::profile_policy},
    {.name = "--binarize", .metavar = "METHOD", .scope = CommandSet{Command::process}, .group = "Processing arguments", .domain = "sauvola for bw; fixed|sauvola", .methods = "B02,B03", .description = "Requires explicit --output-mode bw. B02/B03 use stored 1/2/4/8-bit grayscale PNG samples without transparency and output 8-bit black/white; no color or gamma conversion is applied.", .binding = &Invocation::binarize},
    {.name = "--fixed-threshold", .metavar = "T", .scope = CommandSet{Command::process}, .group = "Processing arguments", .domain = "0.50; finite `[0,1]`", .methods = "B03", .description = "B03 only. Normalized grayscale threshold; black iff sample/255 <= T. Rejected for Sauvola.", .binding = &Invocation::fixed_threshold},
    {.name = "--sauvola-window", .metavar = "PIXELS", .scope = CommandSet{Command::process}, .group = "Processing arguments", .domain = "31; odd integer `[3,4095]`", .methods = "B02", .description = "B02 only. Centered square window with REFLECT_101 borders; a singleton dimension repeats its sample.", .binding = &Invocation::sauvola_window},
    {.name = "--sauvola-k", .metavar = "K", .scope = CommandSet{Command::process}, .group = "Processing arguments", .domain = "0.2; finite `[0,1]`", .methods = "B02", .description = "B02 only. Weight in T=m*(1+k*(s/(255*R)-1)), using population standard deviation in stored byte units.", .binding = &Invocation::sauvola_k},
    {.name = "--sauvola-r", .metavar = "R", .scope = CommandSet{Command::process}, .group = "Processing arguments", .domain = "0.5; finite `[1/255,1]`", .methods = "B02", .description = "B02 only. Normalized deviation scale: 0.5 means 127.5 in byte units, not 128. Black iff sample <= T; no threshold rounding or clipping.", .binding = &Invocation::sauvola_r},
    {.name = "--json", .metavar = "", .scope = CommandSet::all(), .group = "Presentation arguments", .domain = "False", .methods = "", .description = "Render one JSON response on stdout and no diagnostic text on stderr. Flush the selected stream before returning. JSON exit_code describes the rendered command outcome; response-delivery failure can instead end the process with exit 5. Check both the response and process status. A missing/incomplete response or exit 5 does not prove that publication did not commit; do not retry blindly.", .binding = &Invocation::json},
    {.name = "--help", .metavar = "", .scope = CommandSet::all(), .group = "Presentation arguments", .domain = "N/A", .methods = "", .description = "Renders help and exits without opening input or creating output.", .binding = &Invocation::help},
    {.name = "--version", .metavar = "", .scope = CommandSet{Command::root}, .group = "Presentation arguments", .domain = "N/A", .methods = "", .description = "Human-readable alias of `version`.", .binding = &Invocation::root_version},
    {.name = "--illumination", .metavar = "MODE", .scope = CommandSet{Command::process}, .group = "Illumination arguments", .domain = "off; off|surface|auto", .methods = "I01", .description = "Select I01 for continuous preserve/gray output only. Off is the default; auto may skip for explicitly reported applicability predicates.", .binding = &Invocation::illumination},
    {.name = "--background-strength", .metavar = "A", .scope = CommandSet{Command::process}, .group = "Illumination arguments", .domain = "1; finite [0,1]", .methods = "I01", .description = "Exponent applied to the I01 gain; 1 corrects the fitted background fully within the gain cap. Zero is an exact photometric no-op after parameter and mask validation.", .binding = &Invocation::background_strength},
    {.name = "--background-max-gain", .metavar = "G", .scope = CommandSet{Command::process}, .group = "Illumination arguments", .domain = "2; finite [1,4]", .methods = "I01", .description = "Maximum I01 multiplicative gain. One is an exact photometric no-op.", .binding = &Invocation::background_max_gain},
    {.name = "--background-target", .metavar = "TARGET", .scope = CommandSet{Command::process}, .group = "Illumination arguments", .domain = "source; source or finite [0.1,1]", .methods = "I01", .description = "Linear-light target. Source uses the fitted background nearest-rank 90th percentile, not forced paper white.", .binding = &Invocation::background_target},
    {.name = "--background-cell", .metavar = "SIZE", .scope = CommandSet{Command::process}, .group = "Illumination arguments", .domain = "auto; auto or integer [8,512]", .methods = "I01", .description = "Cell edge in oriented pixels. Auto is round(min(width,height)/24), clamped to [16,256]. Resource refusal never changes this value.", .binding = &Invocation::background_cell},
    {.name = "--background-quantile", .metavar = "Q", .scope = CommandSet{Command::process}, .group = "Illumination arguments", .domain = "0.90; finite [0.75,0.99]", .methods = "I01", .description = "Nearest-rank quantile of all eligible cell samples; protected samples are excluded.", .binding = &Invocation::background_quantile},
    {.name = "--background-smooth", .metavar = "BETA", .scope = CommandSet{Command::process}, .group = "Illumination arguments", .domain = "1; finite [0.1,20]", .methods = "I01", .description = "Positive grid-Laplacian weight for fitting the logarithmic background.", .binding = &Invocation::background_smooth},
    {.name = "--protect-mask", .metavar = "PATH", .scope = CommandSet{Command::process}, .group = "Protection arguments", .domain = "Absent", .methods = "I01,D01", .description = "1-bit or 8-bit grayscale PNG mask matching oriented source dimensions. Nonzero protects. Any alpha must be fully opaque; mask orientation must be normal. The mask is validated even when illumination and denoising are disabled.", .binding = &Invocation::protect_mask},
    {.name = "--denoise", .metavar = "METHOD", .scope = CommandSet{Command::process}, .group = "Denoising arguments", .domain = "off; off|nlm", .methods = "D01", .description = "Opt-in bounded 16-bit luminance NLM-L1 for continuous PNG/JPEG after I01. No binary denoising.", .binding = &Invocation::denoise},
    {.name = "--denoise-blend", .metavar = "A", .scope = CommandSet{Command::process}, .group = "Denoising arguments", .domain = "0.5; finite `[0,1]`", .methods = "D01", .description = "NLM only. Blend once; zero preserves entering samples after source/mask validation.", .binding = &Invocation::denoise_blend},
    {.name = "--nlm-h", .metavar = "H", .scope = CommandSet{Command::process}, .group = "Denoising arguments", .domain = "3; finite `[0.1,25]`", .methods = "D01", .description = "NLM only. Equivalent 8-bit perceptual strength; native float strength is 257 times float(H). Higher strengths may remove marks.", .binding = &Invocation::nlm_h},
    {.name = "--nlm-patch", .metavar = "PIXELS", .scope = CommandSet{Command::process}, .group = "Denoising arguments", .domain = "7; odd integer `[3,15]`", .methods = "D01", .description = "NLM only. Square patch width.", .binding = &Invocation::nlm_patch},
    {.name = "--nlm-search", .metavar = "PIXELS", .scope = CommandSet{Command::process}, .group = "Denoising arguments", .domain = "21; odd integer `[7,41]`", .methods = "D01", .description = "NLM only. Search at least patch; active processing requires fit in smaller oriented dimension.", .binding = &Invocation::nlm_search},
});
// clang-format on
static_assert(
    std::ranges::all_of(option_catalog,
                        [](const auto& option) {
                            return std::visit(
                                [&option](auto binding) {
                                    return std::is_same_v<decltype(binding), bool Invocation::*> ==
                                           option.metavar.empty();
                                },
                                option.binding);
                        }),
    "Option spelling and typed binding must agree on flag/value semantics");
} // namespace docenhance::contract
