# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MPL-2.0
# Compile a checked allocation-order correction without modifying the locked source cache.
if(NOT DOCENHANCE_OPENCV_OWNED_MAT_STORAGE)
  message(FATAL_ERROR "D01 requires the reviewed Mat allocation ownership correction")
endif()
set(de_matrix_directory "${CMAKE_SOURCE_DIR}/modules/core/src")
set(de_matrix_source "${de_matrix_directory}/matrix.cpp")
file(SHA256 "${de_matrix_source}" de_matrix_digest)
if(NOT de_matrix_digest STREQUAL DOCENHANCE_OPENCV_MATRIX_SHA256)
  message(FATAL_ERROR "Review Mat allocation ownership against the new locked OpenCV source")
endif()
set(de_photo_directory "${CMAKE_SOURCE_DIR}/modules/photo/src")
file(SHA256 "${de_photo_directory}/denoising.cpp" de_denoising_digest)
file(SHA256 "${de_matrix_directory}/parallel.cpp" de_parallel_digest)
if(NOT de_denoising_digest STREQUAL DOCENHANCE_OPENCV_DENOISING_SHA256
   OR NOT de_parallel_digest STREQUAL DOCENHANCE_OPENCV_PARALLEL_SHA256)
  message(FATAL_ERROR "Review the native NLM single-stripe and resource contracts against the new source")
endif()
file(READ "${de_matrix_source}" de_matrix)
set(de_before "        uchar* data = data0 ? (uchar*)data0 : (uchar*)fastMalloc(total);\n        UMatData* u = new UMatData(this);")
set(de_after "        std::unique_ptr<UMatData> owner(new UMatData(this));\n        uchar* data = data0 ? (uchar*)data0 : (uchar*)fastMalloc(total);\n        UMatData* u = owner.release();")
string(FIND "${de_matrix}" "${de_before}" de_at)
if(de_at EQUAL -1)
  message(FATAL_ERROR "The reviewed Mat allocation sequence is absent")
endif()
string(REPLACE "${de_before}" "${de_after}" de_matrix "${de_matrix}")
string(REPLACE "#include \"precomp.hpp\"" "#include \"precomp.hpp\"\n#include <memory>" de_matrix "${de_matrix}")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/owned-source")
set(de_owned "${CMAKE_BINARY_DIR}/owned-source/matrix.cpp")
file(WRITE "${de_owned}" "${de_matrix}")
get_target_property(de_core_sources opencv_core SOURCES)
list(FIND de_core_sources "${de_matrix_source}" de_index)
if(de_index EQUAL -1)
  message(FATAL_ERROR "The reviewed native Mat source registration is absent")
endif()
list(REMOVE_ITEM de_core_sources "${de_matrix_source}")
list(APPEND de_core_sources "${de_owned}")
set_property(TARGET opencv_core PROPERTY SOURCES "${de_core_sources}")
target_include_directories(opencv_core PRIVATE "${CMAKE_SOURCE_DIR}/modules/core/src")
