#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MPL-2.0
"""Generate typed option descriptors and target-reference docs from the reviewed contract."""

from __future__ import annotations

import argparse
import json
import re
import textwrap
from pathlib import Path
from typing import Any

from method_metadata import implemented, metadata_outputs, support_matrix

ROOT = Path(__file__).resolve().parents[1]
# The option fields, in the order the generated descriptor declares them. "scope" is typed and is
# therefore rendered separately from the string fields.
FIELDS = ("name", "metavar", "scope", "group", "domain", "methods", "description")
STRING_FIELDS = tuple(field for field in FIELDS if field != "scope")
HEADER_PREAMBLE = (
    "// SPDX-FileCopyrightText: 2026 Ervins Strauhmanis\n"
    "// SPDX-License-Identifier: MPL-2.0\n"
    "// Generated by tools/generate_spec.py. Edit spec/cli-contract.json instead.\n"
    "#pragma once\n"
    '#include "docenhance/contract/command.hpp"\n\n'
    "#include <algorithm>\n#include <array>\n#include <optional>\n#include <string>\n"
    "#include <string_view>\n#include <type_traits>\n#include <variant>\n"
    "namespace docenhance::contract {\n"
)
REFERENCE_PREAMBLE = (
    "# Argument contract\n\n"
    "> Generated from `spec/cli-contract.json` by `tools/generate_spec.py`. These are the arguments"
    " the command line parses and documents today. See [current CLI behavior](cli.md) and"
    " [status](status.md) for supported behavior.\n\n"
    "P = process.\n\n"
)
METHODS_PREAMBLE = (
    "# Methods\n\n"
    "> Generated from `spec/method-contract.json` by `tools/generate_spec.py`. Only methods marked"
    " **implemented** appear in `docenhance methods`; every other entry remains a reviewed design"
    " target until its contract, tests, and fixtures exist.\n\n"
)


FIXED_TOKENS = (
    "--help",
    "--json",
    "--version",
    "--",
    "auto",
    "all",
    "off",
    "1-3",
    "0.5",
    "preserve",
    "gray",
    "bw",
    "embedded",
    "srgb",
    "16",
    "fixed",
    "sauvola",
    "surface",
    "source",
    "31",
    "0.2",
)


class ContractError(ValueError):
    """The reviewed contract violates a structural invariant."""


def scope_expression(scope: str, symbols: dict[str, str]) -> str:
    """Turn a reviewed scope such as "P,L" into the typed set of commands it means."""
    if scope == "All commands":
        return "CommandSet::all()"
    if scope == "Root only":
        return "CommandSet{Command::root}"
    names = []
    for symbol in scope.split(","):
        if symbol not in symbols:
            msg = f"Option scope '{scope}' uses symbol '{symbol}', which no command declares"
            raise ContractError(msg)
        names.append(symbols[symbol])
    return "CommandSet{" + ", ".join(f"Command::{name}" for name in names) + "}"


def cxx_string(value: str) -> str:
    """Render one C++ string literal, splitting long word-boundary-safe usages."""
    parts = textwrap.wrap(value, width=60, break_long_words=False, break_on_hyphens=False)
    return "\n               ".join(
        json.dumps(part + (" " if index + 1 < len(parts) else ""))
        for index, part in enumerate(parts)
    )


def render_header(contract: dict[str, Any], response_version: int, confirmed_limit: int) -> str:
    """Render the C++ contract: the command usage lines and the typed option catalog."""
    if set(contract) != {"schema_version", "value_grammar", "commands", "options", "input_support"}:
        msg = "The CLI authoring contract must use exactly the current fields"
        raise ContractError(msg)
    commands: dict[str, dict[str, str]] = contract["commands"]
    symbols = {
        command["scope_symbol"]: name
        for name, command in commands.items()
        if command["scope_symbol"]
    }
    text = HEADER_PREAMBLE
    text += f"inline constexpr unsigned response_schema_version = {response_version}U;\n"
    text += f"inline constexpr unsigned response_confirmed_limit = {confirmed_limit}U;\n"
    support_matrix(contract["input_support"])
    text += "inline constexpr auto input_support = std::to_array<InputSupport>({\n"
    for item in contract["input_support"]:
        text += (
            f"    {{.format = {json.dumps(item['format'])}, "
            f".binary = {str(item['binary']).lower()}}},\n"
        )
    text += "});\n"
    text += "// The usage line of every command, as the reviewed contract states it.\n"
    text += "[[nodiscard]] constexpr std::string_view command_usage(Command command) noexcept {\n"
    text += "    switch (command) {\n"
    for name, command in commands.items():
        usage = cxx_string(command["usage"])
        text += f"    case Command::{name}:\n        return {usage};\n"
    text += "    }\n    return {};\n}\n"
    text += "using OptionBinding = std::variant<bool Invocation::*, std::string Invocation::*,\n"
    text += "                                   std::optional<std::string> Invocation::*>;\n"
    text += "struct OptionDescriptor {\n"
    text += "".join(
        f"    {'CommandSet' if field == 'scope' else 'std::string_view'} {field};\n"
        for field in FIELDS
    )
    text += "    OptionBinding binding;\n"
    text += "};\n// Descriptions are long single-line literals; keep one option per line.\n"
    text += "// clang-format off\n"
    text += "inline constexpr auto option_catalog = std::to_array<OptionDescriptor>({\n"
    bindings = [option.get("binding") for option in contract["options"]]
    if any(
        not isinstance(binding, str) or not re.fullmatch(r"[a-z][a-z0-9_]*", binding)
        for binding in bindings
    ) or len(set(bindings)) != len(bindings):
        msg = "Every option requires a unique typed invocation member binding"
        raise ContractError(msg)
    for option in contract["options"]:
        fields = {
            **{f: json.dumps(option[f], ensure_ascii=True) for f in STRING_FIELDS},
            "scope": scope_expression(option["scope"], symbols),
        }
        row = ", ".join(f".{field} = {fields[field]}" for field in FIELDS)
        row += f", .binding = &Invocation::{option['binding']}"
        text += "    {" + row + "},\n"
    text += "});\n// clang-format on\n"
    text += """static_assert(
    std::ranges::all_of(option_catalog,
                        [](const auto& option) {
                            return std::visit(
                                [&option](auto binding) {
                                    return std::is_same_v<decltype(binding), bool Invocation::*> ==
                                           option.metavar.empty();
                                },
                                option.binding);
                        }),
    "Option spelling and typed binding must agree on flag/value semantics");
"""
    return text + "} // namespace docenhance::contract\n"


def render_reference(contract: dict[str, Any]) -> str:
    """Render docs/cli-contract.md."""
    options: list[dict[str, str]] = contract["options"]
    text = REFERENCE_PREAMBLE + "## Commands\n\n"
    for name, command in contract["commands"].items():
        text += f"- `{name}` — `{command['usage']}`\n"
        if description := command.get("description"):
            text += f"  {description}\n"
    text += "\n## Input support\n\n"
    for item in support_matrix(contract["input_support"]):
        modes = ", ".join(f"`{mode}`" for mode in item["output_modes"])
        text += f"- `{item['format']}`: {modes}.\n"
    text += "\n## Value grammar\n\n"
    for name, rule in contract["value_grammar"].items():
        text += f"**{name.capitalize()} values.** {rule}\n\n"
    for o in options:
        metavar = f" {o['metavar']}" if o["metavar"] else ""
        text += f"## `{o['name']}{metavar}`\n\n"
        text += f"**Scope:** {o['scope']}. **Domain/default:** {o['domain']}.\n\n"
        text += f"{o['description']}\n\n"
        if o["methods"]:
            text += f"**Applicable methods:** {o['methods']}.\n\n"
    return text.rstrip() + "\n"


def render_methods(methods: list[dict[str, Any]]) -> str:
    """Render docs/methods.md."""
    text = METHODS_PREAMBLE
    for method in methods:
        text += f"## {method['id']} — {method['name']}\n\n"
        text += f"Status: **{method['status']}**.\n\n"
        references = ", ".join(f"`{x}`" for x in method.get("arguments", []))
        references = references or "See geometry/common options in the target contract"
        text += f"Method-specific argument references: {references}.\n\n"
    return text.rstrip() + "\n"


def render_cli_dictionary(contract: dict[str, Any], methods: list[dict[str, Any]]) -> str:
    """Render the CLI fuzzing dictionary: every command, option name and common value."""
    commands = [name for name in contract["commands"] if name != "root"]
    tokens = [
        *commands,
        *FIXED_TOKENS,
        *(entry["selector"] for entry in implemented(methods, contract["options"])),
        *(option["name"] for option in contract["options"]),
    ]
    text = "# Generated by tools/generate_spec.py from spec/cli-contract.json.\n"
    return text + "".join(f"{json.dumps(token)}\n" for token in dict.fromkeys(tokens))


def outputs() -> dict[Path, str]:
    """Return every generated file's path and expected content."""
    contract = json.loads((ROOT / "spec/cli-contract.json").read_text(encoding="utf-8"))
    options = contract["options"]
    methods = json.loads((ROOT / "spec/method-contract.json").read_text(encoding="utf-8"))
    schema = json.loads((ROOT / "spec/command-response.schema.json").read_text(encoding="utf-8"))
    names = [option["name"] for option in options]
    if not names or len(names) != len(set(names)):
        msg = "The reviewed command contract must contain unique options"
        raise ContractError(msg)
    return {
        ROOT / "include/docenhance/contract/cli_contract.hpp": render_header(
            contract,
            schema["properties"]["schema_version"]["const"],
            next(
                branch["properties"]["confirmed"]["maxItems"]
                for branch in schema["oneOf"]
                if "confirmed" in branch.get("properties", {})
            ),
        ),
        ROOT / "docs/cli-contract.md": render_reference(contract),
        ROOT / "docs/methods.md": render_methods(methods["methods"]),
        ROOT / "fuzz/dict/cli.dict": render_cli_dictionary(contract, methods["methods"]),
        **metadata_outputs(ROOT, methods["methods"], options, contract["input_support"]),
    }


def main() -> int:
    """Write the generated files, or with --check report any that are stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failed = []
    for path, text in outputs().items():
        encoded = text.encode("utf-8")
        matches = path.is_file() and path.read_bytes() == encoded
        if args.check:
            if not matches:
                failed.append(str(path.relative_to(ROOT)))
        elif not matches:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(encoded)
    if failed:
        print("Stale generated files: " + ", ".join(failed))
        return 1
    print("Generated contract files are current" if args.check else "Generated contract files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
