# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MIT
# Link-edge enforcement, driven by spec/architecture.json rather than by lists repeated here.
# Every first-party target registers its layer, its files and its links; a link outside the layer's
# declared dependencies or declared packages fails the configure step. The same registration is
# written to the build tree so tools/check_architecture.py can hold the real include graph against
# the links the build claims.
file(READ "${PROJECT_SOURCE_DIR}/spec/architecture.json" DE_ARCHITECTURE_JSON)
set_property(GLOBAL PROPERTY DE_ARCHITECTURE_TARGETS "")

# The layer a first-party library target belongs to, or an empty string.
function(de_layer_of_target target out)
  string(JSON layers GET "${DE_ARCHITECTURE_JSON}" "layers")
  string(JSON count LENGTH "${layers}")
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON layer MEMBER "${layers}" ${index})
    string(JSON declared GET "${layers}" "${layer}" "target")
    if(declared STREQUAL target)
      set(${out} "${layer}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out} "" PARENT_SCOPE)
endfunction()

# The declared package a third-party target belongs to, or an empty string.
function(de_package_of_target target out)
  string(JSON packages GET "${DE_ARCHITECTURE_JSON}" "packages")
  string(JSON count LENGTH "${packages}")
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON package MEMBER "${packages}" ${index})
    string(JSON targets GET "${packages}" "${package}" "targets")
    string(JSON target_count LENGTH "${targets}")
    math(EXPR target_last "${target_count} - 1")
    foreach(target_index RANGE ${target_last})
      string(JSON candidate GET "${targets}" ${target_index})
      if(candidate STREQUAL target)
        set(${out} "${package}" PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endforeach()
  set(${out} "" PARENT_SCOPE)
endfunction()

# Whether a layer names another layer in "uses", or a package in "external".
function(de_layer_allows layer field value out)
  string(JSON allowed ERROR_VARIABLE missing GET "${DE_ARCHITECTURE_JSON}" "layers" "${layer}" "${field}")
  set(${out} FALSE PARENT_SCOPE)
  if(missing)
    return()
  endif()
  string(JSON count LENGTH "${allowed}")
  if(count EQUAL 0)
    return()
  endif()
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON entry GET "${allowed}" ${index})
    if(entry STREQUAL value)
      set(${out} TRUE PARENT_SCOPE)
      return()
    endif()
  endforeach()
endfunction()

# Record a first-party target and reject any link the manifest does not allow for its layer.
function(de_register_target target)
  cmake_parse_arguments(PARSE_ARGV 1 arg "" "LAYER" "SOURCES;HEADERS;LINKS")
  string(JSON ignored ERROR_VARIABLE unknown GET "${DE_ARCHITECTURE_JSON}" "layers" "${arg_LAYER}")
  if(unknown)
    message(FATAL_ERROR "${target} declares layer '${arg_LAYER}', which spec/architecture.json does not define")
  endif()
  foreach(link IN LISTS arg_LINKS)
    de_layer_of_target("${link}" link_layer)
    if(link_layer)
      de_layer_allows("${arg_LAYER}" "uses" "${link_layer}" allowed)
      if(NOT allowed AND NOT link_layer STREQUAL arg_LAYER)
        message(FATAL_ERROR "Forbidden architecture edge: ${arg_LAYER} (${target}) -> ${link_layer} (${link})")
      endif()
    else()
      de_package_of_target("${link}" package)
      if(NOT package)
        message(FATAL_ERROR "${target} links ${link}, which spec/architecture.json does not declare as a package")
      endif()
      de_layer_allows("${arg_LAYER}" "external" "${package}" allowed)
      if(NOT allowed)
        message(FATAL_ERROR "Forbidden package edge: ${arg_LAYER} (${target}) -> ${package} (${link})")
      endif()
    endif()
  endforeach()
  set(files "")
  foreach(file IN LISTS arg_SOURCES arg_HEADERS)
    cmake_path(ABSOLUTE_PATH file BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE OUTPUT_VARIABLE absolute)
    list(APPEND files "${absolute}")
  endforeach()
  string(JSON record SET "{}" "layer" "\"${arg_LAYER}\"")
  string(JSON record SET "${record}" "files" "[]")
  de_json_array(record "files" "${files}")
  string(JSON record SET "${record}" "links" "[]")
  de_json_array(record "links" "${arg_LINKS}")
  get_property(records GLOBAL PROPERTY DE_ARCHITECTURE_TARGETS)
  list(APPEND records "\"${target}\": ${record}")
  set_property(GLOBAL PROPERTY DE_ARCHITECTURE_TARGETS "${records}")
endfunction()

# Fill a JSON array member of a record with a CMake list of strings.
function(de_json_array record_variable member values)
  set(record "${${record_variable}}")
  set(index 0)
  foreach(value IN LISTS values)
    string(JSON record SET "${record}" "${member}" ${index} "\"${value}\"")
    math(EXPR index "${index} + 1")
  endforeach()
  set(${record_variable} "${record}" PARENT_SCOPE)
endfunction()

# A native build must instantiate every layer. An isolated build must instantiate every layer
# reachable from its explicitly named root(s); omission is never an unchecked target waiver.
function(de_write_architecture_targets path)
  cmake_parse_arguments(PARSE_ARGV 1 arg "" "" "ROOTS")
  set(required ${arg_ROOTS})
  if(required)
    set(pending ${required})
    while(pending)
      list(POP_FRONT pending layer)
      string(JSON uses GET "${DE_ARCHITECTURE_JSON}" layers "${layer}" uses)
      string(JSON count LENGTH "${uses}")
      if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE ${last})
          string(JSON used GET "${uses}" ${index})
          if(NOT used IN_LIST required)
            list(APPEND required "${used}")
            list(APPEND pending "${used}")
          endif()
        endforeach()
      endif()
    endwhile()
  else()
    string(JSON count LENGTH "${DE_ARCHITECTURE_JSON}" layers)
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
      string(JSON layer MEMBER "${DE_ARCHITECTURE_JSON}" layers ${index})
      list(APPEND required "${layer}")
    endforeach()
  endif()
  foreach(layer IN LISTS required)
    string(JSON declared GET "${DE_ARCHITECTURE_JSON}" layers "${layer}" target)
    if(NOT TARGET ${declared})
      message(FATAL_ERROR "Required layer '${layer}' (${declared}) has no target")
    endif()
  endforeach()
  get_property(records GLOBAL PROPERTY DE_ARCHITECTURE_TARGETS)
  list(JOIN records ",\n  " body)
  file(WRITE "${path}" "{\n  ${body}\n}\n")
endfunction()
