# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MPL-2.0
# A configuration binding, not a compiler/source security endorsement or an RSS guarantee.
include_guard(GLOBAL)
if(DE_SUPERBUILD)
  set(de_owner "${PROJECT_BINARY_DIR}")
else()
  if(NOT DE_SUPERBUILD_BINARY)
    message(FATAL_ERROR "The application is configured only through its owning superbuild")
  endif()
  file(REAL_PATH "${DE_SUPERBUILD_BINARY}/app" expected)
  file(REAL_PATH "${PROJECT_BINARY_DIR}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "The application build directory must be the owner's app directory")
  endif()
  set(de_owner "${DE_SUPERBUILD_BINARY}")
endif()
file(REAL_PATH "${de_owner}" DE_BUILD_OWNER)
cmake_path(ABSOLUTE_PATH DE_DEPENDENCY_PREFIX BASE_DIRECTORY "${PROJECT_BINARY_DIR}" NORMALIZE OUTPUT_VARIABLE actual)
cmake_path(GET actual PARENT_PATH parent_directory)
cmake_path(GET actual FILENAME leaf)
if(NOT IS_DIRECTORY "${parent_directory}" OR NOT leaf STREQUAL "prefix" OR IS_SYMLINK "${actual}")
  message(FATAL_ERROR "Each superbuild owns exactly its private prefix directory: ${actual}")
endif()
file(REAL_PATH "${parent_directory}" actual_parent)
if(NOT actual_parent STREQUAL DE_BUILD_OWNER)
  message(FATAL_ERROR "Each superbuild owns exactly its private prefix directory under ${DE_BUILD_OWNER}: ${actual}")
endif()
file(MAKE_DIRECTORY "${DE_DEPENDENCY_PREFIX}")
set(de_identity "{}")
function(de_identity_field key value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  string(JSON next SET "${de_identity}" "${key}" "\"${value}\"")
  set(de_identity "${next}" PARENT_SCOPE)
endfunction()
foreach(path IN ITEMS "${PROJECT_SOURCE_DIR}" "${DE_SOURCE_CACHE}" "${DE_DEPENDENCY_PREFIX}")
  file(REAL_PATH "${path}" resolved)
  de_identity_field("${path}" "${resolved}")
endforeach()
foreach(name IN ITEMS CMAKE_GENERATOR CMAKE_BUILD_TYPE CMAKE_SYSTEM_NAME CMAKE_SYSTEM_PROCESSOR
    CMAKE_OSX_DEPLOYMENT_TARGET CMAKE_OSX_ARCHITECTURES CMAKE_OSX_SYSROOT CMAKE_MSVC_RUNTIME_LIBRARY
    DE_CXX_STANDARD DE_TOOLCHAIN DE_BUILD_TESTS DE_BUILD_TOOLS DE_WARNINGS_AS_ERRORS
    DE_ENABLE_CLANG_TIDY DE_ENABLE_ASAN DE_ENABLE_UBSAN DE_ENABLE_TSAN DE_ENABLE_IPO
    DE_ENABLE_FUZZING DE_FUZZ_ONLY DE_FUZZ_ENGINE)
  if(DEFINED ${name})
    de_identity_field("${name}" "${${name}}")
  else()
    de_identity_field("${name}" "")
  endif()
endforeach()
foreach(language IN ITEMS C CXX)
  foreach(suffix IN ITEMS COMPILER COMPILER_ID COMPILER_VERSION FLAGS FLAGS_DEBUG FLAGS_RELEASE FLAGS_RELWITHDEBINFO)
    set(name "CMAKE_${language}_${suffix}")
    if(DEFINED ${name})
    de_identity_field("${name}" "${${name}}")
  else()
    de_identity_field("${name}" "")
  endif()
  endforeach()
  file(SHA256 "${CMAKE_${language}_COMPILER}" digest)
  de_identity_field("${language}_compiler_sha256" "${digest}")
endforeach()
foreach(name IN ITEMS CMAKE_MAKE_PROGRAM CMAKE_COMMAND)
  file(SHA256 "${${name}}" digest)
  de_identity_field("${name}_sha256" "${digest}")
endforeach()
if(APPLE)
  file(REAL_PATH "${CMAKE_OSX_SYSROOT}" sdk)
  de_identity_field(sdk "${sdk}")
  if(EXISTS "${sdk}/SDKSettings.json")
    file(SHA256 "${sdk}/SDKSettings.json" digest)
    de_identity_field(sdk_settings_sha256 "${digest}")
  endif()
endif()
set(de_recipe_files deps/tools.json deps/lock.json deps/features.json
  cmake/BuildPolicy.cmake cmake/BuildEnvironment.cmake cmake/BuildIdentity.cmake cmake/CompilerPolicy.cmake
  cmake/Options.cmake cmake/Superbuild.cmake cmake/DependencyPlan.cmake cmake/NativeHardening.cmake
  cmake/DependencyPaths.cmake cmake/DependencyFeatures.cmake cmake/Dependencies.cmake cmake/ProjectOptions.cmake
  cmake/dependencies/picosha2/CMakeLists.txt cmake/dependencies/json/CMakeLists.txt
  cmake/dependencies/zlib/CMakeLists.txt cmake/dependencies/tiff/CMakeLists.txt
  cmake/dependencies/tiff/docenhance_tiff.h)
file(GLOB de_hooks RELATIVE "${PROJECT_SOURCE_DIR}" "${PROJECT_SOURCE_DIR}/cmake/opencv-hooks/*.cmake")
list(APPEND de_recipe_files ${de_hooks})
foreach(name IN LISTS de_recipe_files)
  file(SHA256 "${PROJECT_SOURCE_DIR}/${name}" digest)
  de_identity_field("${name}" "${digest}")
endforeach()
string(SHA256 DE_BUILD_ID "${de_identity}")
if(NOT DE_SUPERBUILD)
  file(READ "${de_owner}/build-identity.json" parent)
  string(SHA256 parent_id "${parent}")
  if(NOT parent_id STREQUAL DE_BUILD_ID)
    message(FATAL_ERROR "The application configuration differs from its owning superbuild")
  endif()
endif()
set(de_identity_path "${PROJECT_BINARY_DIR}/build-identity.json")
if(EXISTS "${de_identity_path}")
  file(READ "${de_identity_path}" prior)
  if(NOT prior STREQUAL de_identity)
    message(FATAL_ERROR "Build inputs changed. Configure a fresh build directory and private prefix; no cache migration is supported")
  endif()
elseif(DE_EXISTING_BUILD_CACHE OR (DE_SUPERBUILD AND EXISTS "${DE_DEPENDENCY_PREFIX}/include"))
  message(FATAL_ERROR "This populated build tree has no configuration binding. Use a fresh build directory and private prefix")
endif()
# Written only after successful configuration; callers finish declaring their own targets first.
function(de_commit_build_identity)
  file(WRITE "${de_identity_path}.tmp" "${de_identity}")
  file(RENAME "${de_identity_path}.tmp" "${de_identity_path}")
endfunction()
