# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MIT
# Bootstrap policy before project() enables languages and probes the selected SDK.
include_guard(GLOBAL)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../deps/tools.json" de_tools_json)
string(JSON DE_CXX_STANDARD GET "${de_tools_json}" cxx standard)
string(JSON DE_PYTHON_MINIMUM GET "${de_tools_json}" python minimum)
string(JSON DE_NINJA_MINIMUM GET "${de_tools_json}" ninja minimum)
string(JSON DE_MAX_BUILD_JOBS GET "${de_tools_json}" build max_jobs)
set(DE_EXISTING_BUILD_CACHE FALSE)
if(EXISTS "${CMAKE_BINARY_DIR}/CMakeCache.txt")
  set(DE_EXISTING_BUILD_CACHE TRUE)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/BuildEnvironment.cmake")
# CMake's strict project diagnostics also cover modules physically inside its source/build tree.
file(REAL_PATH "${CMAKE_SOURCE_DIR}" de_source_root)
file(REAL_PATH "${CMAKE_BINARY_DIR}" de_binary_root)
file(REAL_PATH "${CMAKE_ROOT}" de_cmake_root)
cmake_path(IS_PREFIX de_source_root "${de_cmake_root}" NORMALIZE de_tool_in_source)
cmake_path(IS_PREFIX de_binary_root "${de_cmake_root}" NORMALIZE de_tool_in_build)
if(de_tool_in_source OR de_tool_in_build)
  message(FATAL_ERROR "Install CMake outside the source and build trees; activate an external tool environment (docs/build.md)")
endif()
if(DEFINED BUILD_TESTING)
  message(FATAL_ERROR "BUILD_TESTING is not a project control; use DE_BUILD_TESTS or the fuzz preset. If this value is cached, select a fresh build tree and private prefix; obsolete configuration is not migrated.")
endif()
if(CMAKE_TOOLCHAIN_FILE OR CMAKE_SYSROOT OR CMAKE_FIND_ROOT_PATH)
  message(FATAL_ERROR "Only native builds are supported; toolchain files and find/sysroot remapping are unsupported")
endif()
if(DEFINED CMAKE_CXX_STANDARD AND NOT CMAKE_CXX_STANDARD EQUAL DE_CXX_STANDARD)
  message(FATAL_ERROR "The C++ standard is owned by deps/tools.json")
endif()
if(DEFINED CMAKE_C_STANDARD AND NOT CMAKE_C_STANDARD EQUAL 11)
  message(FATAL_ERROR "The native C contract requires C11")
endif()
set(CMAKE_CXX_STANDARD "${DE_CXX_STANDARD}")
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
set(de_crt MultiThreaded)
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(de_crt MultiThreadedDebug)
endif()
if(DEFINED CMAKE_MSVC_RUNTIME_LIBRARY AND NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL de_crt)
  message(FATAL_ERROR "The native Windows contract requires the configuration-specific static CRT")
endif()
set(CMAKE_MSVC_RUNTIME_LIBRARY "${de_crt}")
if(CMAKE_HOST_APPLE)
  string(JSON de_macos_minimum GET "${de_tools_json}" macos deployment_target)
  if(CMAKE_OSX_DEPLOYMENT_TARGET AND NOT CMAKE_OSX_DEPLOYMENT_TARGET VERSION_EQUAL de_macos_minimum)
    message(FATAL_ERROR "The macOS deployment target must equal deps/tools.json: ${de_macos_minimum}")
  endif()
  set(CMAKE_OSX_DEPLOYMENT_TARGET "${de_macos_minimum}" CACHE STRING "Reviewed macOS deployment target")
  if(NOT CMAKE_OSX_SYSROOT)
    set(CMAKE_OSX_SYSROOT "macosx" CACHE STRING "SDK shared by the native build and compiler tooling")
  endif()
endif()

function(de_native_flag name output)
  set(value "")
  if(DEFINED ${name})
    string(STRIP "${${name}}" value)
  endif()
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(de_validate_native_configuration)
  if(CMAKE_CROSSCOMPILING OR NOT CMAKE_SYSTEM_NAME STREQUAL CMAKE_HOST_SYSTEM_NAME)
    message(FATAL_ERROR "Only native builds on the configured host are supported")
  endif()
  if(NOT CMAKE_BUILD_TYPE MATCHES "^(Debug|Release|RelWithDebInfo)$")
    message(FATAL_ERROR "Use a reviewed Debug, Release or RelWithDebInfo configuration")
  endif()
  foreach(language IN ITEMS C CXX)
    foreach(suffix IN ITEMS "" _DEBUG _RELEASE _RELWITHDEBINFO _MINSIZEREL)
      set(name "CMAKE_${language}_FLAGS${suffix}")
      de_native_flag("${name}" actual)
      de_native_flag("${name}_INIT" expected)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${name} overrides the native defaults; use the reviewed build options")
      endif()
    endforeach()
    foreach(suffix IN ITEMS COMPILER_ARG1 COMPILER_LAUNCHER COMPILER_TARGET LINKER_LAUNCHER)
      if(CMAKE_${language}_${suffix})
        message(FATAL_ERROR "CMAKE_${language}_${suffix} is outside the native compiler contract")
      endif()
    endforeach()
  endforeach()
  foreach(kind IN ITEMS EXE SHARED MODULE STATIC)
    foreach(suffix IN ITEMS "" _DEBUG _RELEASE _RELWITHDEBINFO _MINSIZEREL)
      set(name "CMAKE_${kind}_LINKER_FLAGS${suffix}")
      de_native_flag("${name}" actual)
      de_native_flag("${name}_INIT" expected)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${name} overrides the native defaults")
      endif()
    endforeach()
  endforeach()
  if(APPLE)
    if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64|ARM64)$")
      set(architecture arm64)
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
      set(architecture x86_64)
    else()
      message(FATAL_ERROR "Only native x86-64 and ARM64 hosts are supported")
    endif()
    if(CMAKE_OSX_ARCHITECTURES AND NOT CMAKE_OSX_ARCHITECTURES STREQUAL architecture)
      message(FATAL_ERROR "The macOS architecture must be the single native host architecture")
    endif()
    set(CMAKE_OSX_ARCHITECTURES "${architecture}" CACHE STRING "Native macOS architecture")
    set(CMAKE_OSX_ARCHITECTURES "${architecture}" PARENT_SCOPE)
  endif()
  foreach(name IN ITEMS DE_WARNINGS_AS_ERRORS DE_ENABLE_CLANG_TIDY)
    if(NOT ${name})
      message(FATAL_ERROR "${name} is required by the project quality contract")
    endif()
  endforeach()
  if(DE_FUZZ_ONLY AND (DE_BUILD_TESTS OR DE_BUILD_TOOLS))
    message(FATAL_ERROR "The isolated fuzz build excludes unit tests and the development probe")
  endif()
endfunction()
