# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MIT
# The actual serial dependency closure, shared by configuration, verification and importing.
include_guard(GLOBAL)
set(DE_SELECTED_DEPENDENCIES zlib jpeg png)
if(DE_BUILD_TOOLS AND NOT DE_FUZZ_ONLY)
  list(APPEND DE_SELECTED_DEPENDENCIES tiff)
endif()
list(APPEND DE_SELECTED_DEPENDENCIES opencv)
if(DE_BUILD_TOOLS AND NOT DE_FUZZ_ONLY)
  list(APPEND DE_SELECTED_DEPENDENCIES leptonica)
endif()
list(APPEND DE_SELECTED_DEPENDENCIES lcms cli11 json picosha2)
if(DE_BUILD_TESTS)
  list(APPEND DE_SELECTED_DEPENDENCIES catch2)
endif()
file(READ "${PROJECT_SOURCE_DIR}/deps/lock.json" de_lock)
string(JSON de_count LENGTH "${de_lock}" dependencies)
math(EXPR de_last "${de_count} - 1")
foreach(i RANGE 0 ${de_last})
  string(JSON name GET "${de_lock}" dependencies ${i} name)
  string(JSON version GET "${de_lock}" dependencies ${i} version)
  set(DE_DEPENDENCY_VERSION_${name} "${version}")
endforeach()
set(de_plan "[]")
set(i 0)
foreach(name IN LISTS DE_SELECTED_DEPENDENCIES)
  string(JSON de_plan SET "${de_plan}" ${i} "\"${name}\"")
  math(EXPR i "${i} + 1")
endforeach()
file(WRITE "${PROJECT_BINARY_DIR}/dependency-plan.json" "${de_plan}\n")
