# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MPL-2.0
# Resolve platform-applicable reviewed feature values into actual dependency arguments.
include_guard(GLOBAL)
file(READ "${PROJECT_SOURCE_DIR}/deps/features.json" de_features)
if(UNIX)
  string(JSON unix_count LENGTH "${de_features}" unix_dependencies)
  math(EXPR unix_last "${unix_count} - 1")
  foreach(i RANGE 0 ${unix_last})
    string(JSON name MEMBER "${de_features}" unix_dependencies ${i})
    string(JSON count LENGTH "${de_features}" unix_dependencies "${name}")
    math(EXPR last "${count} - 1")
    foreach(j RANGE 0 ${last})
      string(JSON key MEMBER "${de_features}" unix_dependencies "${name}" ${j})
      string(JSON value GET "${de_features}" unix_dependencies "${name}" "${key}")
      if(value)
        set(json_value true)
      else()
        set(json_value false)
      endif()
      string(JSON de_features SET "${de_features}" dependencies "${name}" "${key}" "${json_value}")
    endforeach()
  endforeach()
endif()
function(de_dependency_features name binary output)
  set(de_options)
  string(JSON de_count LENGTH "${de_features}" dependencies "${name}")
  if(de_count GREATER 0)
    math(EXPR de_last "${de_count} - 1")
    foreach(i RANGE 0 ${de_last})
      string(JSON key MEMBER "${de_features}" dependencies "${name}" ${i})
      string(JSON value GET "${de_features}" dependencies "${name}" "${key}")
      string(JSON kind TYPE "${de_features}" dependencies "${name}" "${key}")
      string(REPLACE "<BINARY>" "${binary}" value "${value}")
      if(kind STREQUAL "BOOLEAN")
        list(APPEND de_options "-D${key}:BOOL=${value}")
      else()
        list(APPEND de_options "-D${key}:STRING=${value}")
      endif()
    endforeach()
  endif()
  set(${output} "${de_options}" PARENT_SCOPE)
endfunction()
