# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MIT
include_guard(GLOBAL)
file(READ "${PROJECT_SOURCE_DIR}/fuzz/targets.json" de_fuzz_manifest)
# Both callers retain their own build behavior; only declarations come from this shared list.
function(de_register_fuzz_targets mode)
  string(JSON count LENGTH "${de_fuzz_manifest}" targets)
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON name MEMBER "${de_fuzz_manifest}" targets ${index})
    string(JSON source GET "${de_fuzz_manifest}" targets "${name}" source)
    string(JSON link_count LENGTH "${de_fuzz_manifest}" targets "${name}" links)
    math(EXPR link_last "${link_count} - 1")
    set(links)
    foreach(link_index RANGE ${link_last})
      string(JSON link GET "${de_fuzz_manifest}" targets "${name}" links ${link_index})
      list(APPEND links "${link}")
    endforeach()
    if(mode STREQUAL "ENGINE")
      de_fuzz_target(${name} SOURCE "${PROJECT_SOURCE_DIR}/fuzz/${source}" LINKS ${links})
    elseif(mode STREQUAL "REPLAY")
      de_fuzz_replay(${name} SOURCE "${PROJECT_SOURCE_DIR}/fuzz/${source}" LINKS ${links})
    else()
      message(FATAL_ERROR "Unknown fuzz registration mode: ${mode}")
    endif()
  endforeach()
endfunction()
