# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MPL-2.0
# Mandatory native protections, shared by project targets and compiled dependencies.
include_guard(GLOBAL)
if(MSVC)
  set(de_hardening_compile /GS /guard:cf)
  set(de_hardening_link /GUARD:CF /DYNAMICBASE /HIGHENTROPYVA /NXCOMPAT)
else()
  set(de_hardening_compile -fstack-protector-strong)
  set(de_hardening_link)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
      list(APPEND de_hardening_compile -D_FORTIFY_SOURCE=2)
    endif()
    list(APPEND de_hardening_link -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack)
  elseif(NOT APPLE)
    message(FATAL_ERROR "Native hardening is defined only for Linux, macOS and Windows")
  endif()
endif()
set(de_hardening_policy "{}")
foreach(kind IN ITEMS compile link)
  set(values "[]")
  set(index 0)
  foreach(flag IN LISTS de_hardening_${kind})
    string(JSON values SET "${values}" ${index} "\"${flag}\"")
    math(EXPR index "${index} + 1")
  endforeach()
  string(JSON de_hardening_policy SET "${de_hardening_policy}" ${kind} "${values}")
endforeach()
file(GENERATE OUTPUT "${PROJECT_BINARY_DIR}/hardening-policy.json" CONTENT "${de_hardening_policy}\n")

function(de_dependency_flags name output)
  set(c_flags ${de_hardening_compile})
  set(cxx_flags ${de_hardening_compile})
  if(WIN32 AND name STREQUAL "leptonica")
    list(APPEND c_flags /DLEPTONICA_INTERCEPT_ALLOC)
  endif()
  if(DE_FUZZ_ONLY AND name MATCHES "^(png|zlib|lcms|jpeg|opencv)$")
    set(instrumentation -fsanitize=address,undefined,fuzzer-no-link
      -fno-sanitize-recover=all -fno-omit-frame-pointer)
    list(APPEND c_flags ${instrumentation})
    if(name STREQUAL "opencv")
      list(APPEND cxx_flags ${instrumentation})
    endif()
  endif()
  set(arguments)
  foreach(language IN ITEMS C CXX)
    if(language STREQUAL "CXX" AND name MATCHES "^(zlib|jpeg|png|leptonica|lcms)$")
      continue()
    endif()
    if(name MATCHES "^(cli11|json|picosha2)$" OR
       (language STREQUAL "C" AND name STREQUAL "catch2"))
      continue()
    endif()
    if(language STREQUAL "C")
      list(JOIN c_flags " " flags)
    else()
      list(JOIN cxx_flags " " flags)
    endif()
    list(APPEND arguments "-DCMAKE_${language}_FLAGS:STRING=${flags}")
  endforeach()
  if(arguments)
    list(APPEND arguments "-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON")
  endif()
  set(${output} ${arguments} PARENT_SCOPE)
endfunction()
