# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MIT
include_guard(GLOBAL)
option(DE_SUPERBUILD "Build isolated, locked dependencies and then the application" ON)
option(DE_BUILD_TESTS "Build application and native dependency tests" ON)
option(DE_BUILD_TOOLS "Build development-only dependency probe" ON)
option(DE_WARNINGS_AS_ERRORS "Treat first-party warnings as errors" ON)
option(DE_ENABLE_ASAN "Instrument first-party code with AddressSanitizer" OFF)
option(DE_ENABLE_UBSAN "Instrument first-party code with UndefinedBehaviorSanitizer" OFF)
option(DE_ENABLE_TSAN "Instrument first-party code with ThreadSanitizer" OFF)
option(DE_ENABLE_FUZZING "Build the fuzz targets (LLVM clang with libFuzzer, or AFL++)" OFF)
option(DE_FUZZ_ONLY "Build only the fuzz targets and the dependencies they need" OFF)
set(DE_FUZZ_SECONDS "60" CACHE STRING "Fuzzing seconds per target, in [1,1800]")
set(DE_FUZZ_JOBS "2" CACHE STRING "Actual concurrent child fuzz tests, in [1,2]")
set(DE_FUZZ_ENGINE "libfuzzer" CACHE STRING "Fuzzing engine: libfuzzer, or afl (AFL++ afl-clang-fast)")
set_property(CACHE DE_FUZZ_ENGINE PROPERTY STRINGS libfuzzer afl)
if(NOT DE_FUZZ_ENGINE MATCHES "^(libfuzzer|afl)$")
  message(FATAL_ERROR "DE_FUZZ_ENGINE must be libfuzzer or afl")
endif()
if(DE_ENABLE_FUZZING AND NOT DE_FUZZ_ONLY)
  message(FATAL_ERROR "Fuzz instrumentation requires the isolated DE_FUZZ_ONLY build; use the fuzz preset")
endif()
if(DE_FUZZ_ONLY AND NOT DE_ENABLE_FUZZING)
  message(FATAL_ERROR "DE_FUZZ_ONLY requires DE_ENABLE_FUZZING")
endif()
if(NOT DE_FUZZ_SECONDS MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "DE_FUZZ_SECONDS must be a positive integer")
endif()
execute_process(COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tools/fuzz_manifest.py"
  --seconds "${DE_FUZZ_SECONDS}" --jobs "${DE_FUZZ_JOBS}"
  OUTPUT_VARIABLE de_fuzz_budget OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
string(JSON DE_FUZZ_TARGET_TIMEOUT GET "${de_fuzz_budget}" target_timeout)
string(JSON DE_FUZZ_CAMPAIGN_TIMEOUT GET "${de_fuzz_budget}" campaign_timeout)
option(DE_ENABLE_IPO "Enable supported interprocedural optimization" OFF)
option(DE_ENABLE_CLANG_TIDY "Run clang-tidy 23+ in warnings-as-errors mode on first-party targets" ON)
set(DE_SOURCE_CACHE "${PROJECT_SOURCE_DIR}/.cache/deps" CACHE PATH "Verified source acquisition cache")
set(DE_DEPENDENCY_PREFIX "${PROJECT_BINARY_DIR}/prefix" CACHE PATH "Isolated dependency install prefix")
set(DE_BUILD_JOBS "2" CACHE STRING "Bounded worker count for each external build")
if(NOT DE_BUILD_JOBS MATCHES "^[1-9][0-9]*$" OR DE_BUILD_JOBS GREATER 64)
  message(FATAL_ERROR "DE_BUILD_JOBS must be in [1,64]")
endif()
if(NOT CMAKE_GENERATOR STREQUAL "Ninja")
  message(FATAL_ERROR "Use the tested Ninja presets (one isolated configuration per directory)")
endif()
execute_process(COMMAND "${CMAKE_MAKE_PROGRAM}" --version OUTPUT_VARIABLE DE_NINJA_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(DE_NINJA_VERSION VERSION_LESS 1.13)
  message(FATAL_ERROR "Ninja >= 1.13 is required; deps/tools.json pins the recommended release")
endif()

if(APPLE)
  # The oldest macOS the shipped binary runs on (docs/decisions.md).
  # deps/tools.json is the single source, shared with the package smoke test.
  if(NOT CMAKE_OSX_DEPLOYMENT_TARGET)
    file(READ "${PROJECT_SOURCE_DIR}/deps/tools.json" de_tools_json)
    string(JSON de_macos_minimum GET "${de_tools_json}" macos deployment_target)
    set(CMAKE_OSX_DEPLOYMENT_TARGET "${de_macos_minimum}" CACHE STRING "Minimum deployment target" FORCE)
  endif()
  if(NOT CMAKE_OSX_ARCHITECTURES)
    set(CMAKE_OSX_ARCHITECTURES "${CMAKE_SYSTEM_PROCESSOR}" CACHE STRING "Single native release architecture" FORCE)
  endif()
endif()
