# SPDX-FileCopyrightText: 2026 Ervins Strauhmanis
# SPDX-License-Identifier: MIT
set(CPACK_PACKAGE_NAME "docenhance")
set(CPACK_PACKAGE_VENDOR "Ervins Strauhmanis")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "DocEnhance — image processing capabilities are reported at runtime")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_FILE_NAME "docenhance-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_CHECKSUM SHA256)
set(CPACK_PACKAGE_DIRECTORY "${PROJECT_SOURCE_DIR}/dist")
set(CPACK_GENERATOR TGZ)
set(CPACK_VERBATIM_VARIABLES TRUE)
